apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
spec:
  replicas: 2  # Number of pods to run
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: nipunat99/calculator-microservice:v2  # Updated image version
        ports:
        - containerPort: 3000
