apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  type: NodePort  # Allows external access
  selector:
    app: calculator
  ports:
  - port: 80  # External port
    targetPort: 3000  # Port inside the container
    nodePort: 30080  # NodePort for external access
